# Etapa de construcción
FROM node:20 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa de producción
FROM node:20
WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

COPY --from=builder /app/dist ./dist

# Puerto de exposición y comando para iniciar la aplicación
EXPOSE 3000
CMD ["npm", "run", "start:prod"]
